AppBundle\Entity\Poem:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PoemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        text:
            type: string
            length: '10000'
    lifecycleCallbacks: {  }
